### ISSUE TITLE
Can this repo have GitHub Discussions enabled?

### ISSUE THREAD

**Issue by hollyfromthenexus** [spinnylights/crypt_underworld#7]
Can this repo have GitHub Discussions enabled? I can build and properly run the project now - so I have a few questions relating to how the project works / how I can assist (and idk if those should go in the Issues section).

**Comment by spinnylights** [comment]
Sure! I've never used it before but it does seem like a more reasonable place to discuss general things than the issue tracker. I would probably rather treat the issue tracker more strictly like a ticketing system in the long run (I guess that's kind of its intended use anyhow).
